### ISSUE TITLE
[BUG] Stuck on "downloading metadata"

### ISSUE THREAD

**Issue by NoordenNorth** [hydralauncher/hydra#535] opened 2024-05-28 19:26 UTC
### Describe the bug

I try to download the game and it stays forever in "downloading metadata".

### Steps to Reproduce

Go to "see download options", then "The outer worlds (1.5.0.622 + peril on gorgon + murder on eridianos + multi11) - [DODI Repack]" and right click.

### Expected behavior

I was hoping you would download the game.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/171082293/6053b676-bb06-47c9-84ff-2c37b60cfb51)
![image](https://github.com/hydralauncher/hydra/assets/171082293/3ef0d73e-cf47-41c7-b6ad-434488823862)

### Operating System

Windows 10

### Hydra Version

V1.2.4

### Additional Information

Nothing.

**Comment by daniil2327** [comment] 2024-05-29 15:55
same problem

**Comment by daniil2327** [comment] 2024-05-29 15:56
its not a bug, its problem with torrent

**Comment by x-0D** [comment] 2024-06-02 11:35
Same problem. Unable to download any of torrents. think it's aria2c problem, it doesn't support hashv2 torrent metadata, only v1. Tried "Papers, Please", "Lethal Company", "112 Operator". (With VPN and without VPN) also directly via bundled aria2c binary. qbittorrent download torrents, but not aria2c.

**Comment by zamitto** [comment] 2024-06-02 14:49
> Same problem. Unable to download any of torrents. think it's aria2c problem, it doesn't support hashv2 torrent metadata, only v1. Tried "Papers, Please", "Lethal Company", "112 Operator". (With VPN and without VPN) also directly via bundled aria2c binary. qbittorrent download torrents, but not aria2c.

Are you using some pre-release version? Because aria2 is not in version 1.2.4 yet

**Comment by x-0D** [comment] 2024-06-02 14:53
> > Same problem. Unable to download any of torrents. think it's aria2c problem, it doesn't support hashv2 torrent metadata, only v1. Tried "Papers, Please", "Lethal Company", "112 Operator". (With VPN and without VPN) also directly via bundled aria2c binary. qbittorrent download torrents, but not aria2c.
> 
> Are you using some pre-release version? Because aria2 is not in version 1.2.4 yet
> 
> If you are using a pre-release version, which OS are you on?

MacOS M1 build, found in pending PR

**Comment by zamitto** [comment] 2024-06-02 14:58
@x-0D, could you attach the logs? We are trying to figure out why aria2 is not working on MacOS
Logs should be at `~/Library/Application Support/Hydra/logs`

You can attach them on #529, as this issue here is not related to aria2

**Comment by Uslipe** [comment] 2024-06-05 05:22
I experienced the same problem with the game:
"Fears to Fathom Ironbark Lookout"
But a few times _(I must have tried to install about 30 times on different occasions)_ the installation starts, but it gets slow enough until the download drops to 0b/s and effectively stops.

**Comment by EvaldoSouza** [comment] 2024-06-09 23:15
I have the same issue with 1.2.4 on Windows. I restarted Hydra and it started to download the game. In my case I suspect it to be some permission, because I have Hydra launch on startup, maybe it don't have permissions to edit or write files.

**Comment by Xxxsusx** [comment] 2024-06-28 00:15
I think it might be some firewall thing connected to aria2c. Because, when i tried downloading a torrent on it for the first time, it showed up a firewall thing asking if the connection to aria2c should be Private or Public network. Not sure if this has anything to do with the metadata bug.

**Comment by JackEnx** [comment] 2024-06-29 01:48
fixed on #722, if the problem persist, please report it

**Closed by JackEnx** 2024-06-29 01:48 UTC
Labels: bug

**Comment by HosachiPL** [comment] 2024-12-01 21:11
Having this issue right now...
