### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lmmqerf** [hydralauncher/hydra#515] opened 2024-05-25 14:20 UTC
### Describe the bug

I launch Hydra and start downloading a game. "Metadata download" appears in the bottom left corner, but nothing happens next.

### Steps to Reproduce

so that I can download the game

### Expected behavior

Download the game in full

### Screenshots

![Hydra 25 05 2024 17_09_47](https://github.com/hydralauncher/hydra/assets/101453913/4d256b42-ada8-4bb5-bfda-231d79f8919d)

### Operating System

Windows 10

### Hydra Version

1.2.4

### Additional Information

I launch hydra and start downloading any game, "metadata download" is written on the bottom left and nothing happens next. what should I do?

**Comment by Davdeveloper933** [comment] 2024-05-26 14:43
This bug is not from the application, but from a specific torrent, which is broken and can no longer be downloaded.

**Comment by retlAairtlA** [comment] 2024-05-27 02:34
It's actually not a bug, depending on the torrent it could be a lack of seeds/peers, a lack of Trackers or there are seeds but they're not online 24/7. (it could even be a bug because you can't configure anything in the hydra torrent, you can't even limit the speed)

**Comment by JackEnx** [comment] 2024-06-29 01:47
fixed on #722, if the problem persist, please report it

**Closed by JackEnx** 2024-06-29 01:47 UTC
Labels: bug
