### ISSUE TITLE
[BUG] Hydra does not generate achievements in Linux

### ISSUE THREAD

**Issue by Gabriel-Rozal** [hydralauncher/hydra#1232] opened 2024-11-13 16:37 UTC
### Describe the bug

Hi, I'm using Hydra on Linux, but when I try to use it to play games to generate achievements, it simply doesn't respond, I'm correctly indexing the wine prefix, I've already tried solutions like Bottles, Steam, Lutris, Heroic Games Launcher, among these solutions the most that happened was redirects to the default .exe app

The tests were with the following games:

- Dark Souls Remastered
- Cuphead
- Red Dead Redemption 1
- Hollow Knight

None of those mentioned presented any results.

Note: The same problem occurs on Arch, Ubuntu and Bazzite, whether on gnome or kde

### Steps to Reproduce

1. Index the .EXE
2. Index the Wine Prefix

### Expected behavior

Redirect to a wine manager, such as lutris and run it, track achievements

### Additional information and data

[error.txt](https://github.com/user-attachments/files/17736014/error.txt)

### Operating System

Linux Distro

### Hydra Version

3.0.5

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by JackEnx** [comment] 2024-11-13 20:15
I don' understand, the problem is generate game achievent, tracking achievents or run game with wine like lutris?

**Comment by zamitto** [comment] 2024-12-24 18:15
Should be fixed by now

**Closed by zamitto** 2024-12-24 18:15 UTC
Labels: bug
