### ISSUE TITLE
[BUG] Can't select .exes to add to liabry on Steam Deck

### ISSUE THREAD

**Issue by TesterHere06** [hydralauncher/hydra#277] opened 2024-05-11 07:53 UTC
**Describe the bug**
The selector for the game on Steam Deck is not recognising .exe types of files, so I can't add them into the launcher

**To Reproduce**

1. Add any game to your libary (not installed from Hydra)
2. Click on it and click on play
3. Try to go to game's folder and apply the .exe file to it
4. Can't apply

**Expected behavior**
Reaching the folder and being able to select .exe file

**Screenshots**
![image](https://github.com/hydralauncher/hydra/assets/81434116/aa45681e-7010-4afb-9e59-ccd109b62fe4)
![image](https://github.com/hydralauncher/hydra/assets/81434116/24a86652-9c26-46e7-8a71-aa01c94dd655)

**Additional context**

- OS: Steam Deck
- Hydra Version: 1.1.0

**Comment by scrlkx** [comment] 2024-05-11 13:55
It seems that there is no support for non-windows OS's files here.

```typescript
  const selectGameExecutable = async () => {
    return window.electron
      .showOpenDialog({
        properties: ["openFile"],
        filters: [
          {
            name: "Game executable",
            extensions: window.electron.platform === "win32" ? ["exe"] : [],
          },
        ],
      })
      .then(({ filePaths }) => {
        if (filePaths && filePaths.length > 0) {
          return filePaths[0];
        }

        return null;
      });
  };
```

This seems strongly related to #279 because we would need this to be able to run Proton/Wine games.

**Comment by scrlkx** [comment] 2024-05-11 19:40
FYI, I was wrong. `extensions: window.electron.platform === "win32" ? ["exe"] : [],` means that any file will be accepeted. Hoewever, for some reason, it's not working properly.

**Comment by zamitto** [comment] 2024-05-12 00:08
See #232 to understand better why the expected behaviour is not happening

**Comment by zamitto** [comment] 2024-05-27 19:11
These should be fixed in the lastest version, if not. Feel free to reopen this issue

**Closed by zamitto** 2024-05-27 19:11 UTC
Labels: bug
