### ISSUE TITLE
Hydra Launcher dont open

### ISSUE THREAD

**Issue by Thalinho456** [hydralauncher/hydra#247] opened 2024-05-09 01:08 UTC
the problem is: "nao foi possivel localizar o ponto de entrada do procedimento DiscardVirtualMemory na biblioteca de veiculo dinamico C:\Users\User\AppData\Local\hydra\app-1.1.0\Hydra.exe.

**Comment by darkjontex** [comment] 2024-05-09 21:01
Wierd. Could give more details? I mean, where did you install Hydra Launcher? its a PC, notebook? Steam Deck?
It looks like driver problem or dependency lib/dll problem in your equipment. In this case, the problem is that you dont have the requirements to install Hydra Launcher.

Video to fix it (in Portuguese) but you can find it in English too.

https://www.youtube.com/watch?v=mU8qpYTkfaM

**Comment by zamitto** [comment] 2024-05-27 01:05
Closing as the problem was on a outdated version and the issue has no updates in 2 weeks

**Closed by zamitto** 2024-05-27 01:05 UTC
