### ISSUE TITLE
[BUG] Miner in repack?

### ISSUE THREAD

**Issue by K14Mua** [hydralauncher/hydra#534] opened 2024-05-28 19:23 UTC
### Describe the bug

I launch the Hydra launcher and immediately along with it the game that I recently installed “supposedly” starts. However, I don’t see the process of this game in the task manager.

### Steps to Reproduce

1. Download and install the A Way Out repack [kaOs Repack]
2. Add the repack executable file to the launcher
3. Try to run the repack through the launcher
profit
4. If desired, close the launcher and launch it again. The game will “start” along with the launcher but is not displayed anywhere in the processes

### Expected behavior

It is expected that when the game starts, the GAME WILL START. In fact, the launcher tells me that the game is running, but I don’t see any evidence of this.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/24901436/b4cb3aed-d4ac-4255-af8e-57a98152aabb)

### Operating System

Windows 11

### Hydra Version

1.2.4

**Comment by zamitto** [comment] 2024-05-29 01:10
I have just downloaded the very same repack you mentioned and it installed and opened successfully. 

Please make sure:
1. No antiviruses deleted any file 
2. There's no incompatibility in your system, like missing driver or anything
3. That you selected the correct `.exe` file of the game on Hydra when clicked the `Play` button

![image](https://github.com/hydralauncher/hydra/assets/167933696/9f757b69-e0f0-44a9-af7b-8c08191a275c)

![image](https://github.com/hydralauncher/hydra/assets/167933696/15905a72-59da-4016-a222-5d6c1e9b83b6)


I should close this issue, as it is not a bug in Hydra or anything

**Closed** 2024-05-31 20:29 UTC
Labels: bug
