### ISSUE TITLE
Real Debrid Support

### ISSUE THREAD

**Issue by nunera** [hydralauncher/hydra#131] opened 2024-04-30 16:09 UTC
Going along with the torrenting theme, allowing real debrid support as a replacement for qbittorrent would add more efficiency and caching for the people who have real debrid.

**Comment by RasecOnerb** [comment] 2024-04-30 17:07
It seems some contributors are working on that.

I think they are adding only Real-Debrid for now. I hope other debrid services will be compatible in the future. (I'm using AllDebrid at the moment, but I might switch to Real-Debrid until AllDebrid is compatible.)

**Comment by lilezek** [comment] 2024-04-30 18:20
I'm the contributor implementing real debrid support. Is there any upside using AllDebrid instead? 

I'm guessing that every debrid has a different API so implementing each one will take some time.

FYI @RasecOnerb

**Comment by edcarlosm** [comment] 2024-05-01 00:10
how do I configure this option

**Comment by lilezek** [comment] 2024-05-01 09:39
@hydralauncher if this is a duplicate of https://github.com/hydralauncher/hydra/issues/51 just close it I guess.

**Comment by hydralauncher** [comment] 2024-05-12 23:59
Closing this since Real Debrid has been implemented on the main branch.

**Closed by hydralauncher** 2024-05-12 23:59 UTC
Labels: duplicate
