### ISSUE TITLE
[BUG] Description of achievements

### ISSUE THREAD

**Issue by Crow-BY** [hydralauncher/hydra#1226] opened 2024-11-10 11:26 UTC
### Describe the bug

Achievements that are initially hidden in Steam in Hydra have no description (only the name), even after receiving

### Steps to Reproduce

Get a similar achievement in the game, mostly these are some story achievements, for example, for completing a chapter of the story

### Expected behavior

Add description to such achievements

### Additional information and data

![Снимок экрана 2024-11-10 142128](https://github.com/user-attachments/assets/be3d6806-383e-4d7d-85f1-a6de093e58b5)

### Operating System

Win 11 Pro 23H2

### Hydra Version

3.0.5

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.
- [X] I have read the [Frequently Asked Questions (FAQ)](https://github.com/hydralauncher/hydra/wiki/FAQ).

**Comment by zamitto** [comment] 2024-11-10 14:34
It is a limitation that Steam puts on it's API. They don't provide descriptions for hidden achievements. We are trying to find alternatives

**Comment by ImFenyx** [comment] 2024-11-10 14:43
> It is a limitation that Steam puts on it's API. They don't provide descriptions for hidden achievements. We are trying to find alternatives

Couldn't this be solved by hiding what the achievement would be and marking it as completed when you complete it?

**Comment by zamitto** [comment] 2024-11-10 21:49
> > It is a limitation that Steam puts on it's API. They don't provide descriptions for hidden achievements. We are trying to find alternatives
> 
> Couldn't this be solved by hiding what the achievement would be and marking it as completed when you complete it?

The point of the issue is that the descriptions for hidden achievements are never available, even after you unlock the achievement.
When you unlock a hidden achievement in Steam, they begin to show the description of that achievement. But their API never provide such descriptions. So, at least for now, we don't have this data to show to users.

**Comment by zamitto** [comment] 2024-12-24 18:16
We added description for hidden achievements in 3.1.0 (only in English unfortunately)

**Closed by zamitto** 2024-12-24 18:16 UTC
Labels: bug
