### ISSUE TITLE
[BUG] No downloads available

### ISSUE THREAD

**Issue by Askorbinoff** [hydralauncher/hydra#672] opened 2024-06-24 18:26 UTC
### Describe the bug

It is written on all the games No downloads available

### Steps to Reproduce

-

### Expected behavior

There must be game downloads

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/98098113/6973264f-f9f2-42a4-9482-c3ddf7e3168c)

### Operating System

Windows 10

### Hydra Version

2.0.1

**Comment by s1nhronn** [comment] 2024-06-24 19:00
![image](https://github.com/hydralauncher/hydra/assets/149201515/8f060bb5-fccd-460a-bf2e-642b39661de7)
+++

**Comment by tanato1293** [comment] 2024-06-24 19:34
O meu também está com esse bug  como resolve

**Comment by zamitto** [comment] 2024-06-24 19:36
Not a bug, you need to add your download sources. Check the community discord server

**Comment by Askorbinoff** [comment] 2024-06-24 19:42
> Not a bug, you need to add your download sources. Check the community discord server

Where to find a discord server?

**Comment by zamitto** [comment] 2024-06-24 19:44
https://discord.gg/TSxymg7JTJ

It's a 100% community server, but they help a lot of users

**Comment by Askorbinoff** [comment] 2024-06-24 19:48
> https://discord.gg/TSxymg7JTJ
> 
> It's a 100% community server, but they help a lot of users

Thanks, I've solved my problem.

**Comment by Gomogomozek2085** [comment] 2024-06-26 22:59
> > https://discord.gg/TSxymg7JTJ
> > It's a 100% community server, but they help a lot of users
> 
> Thanks, I've solved my problem.

Could you please tell me how exactly you solved this problem?

**Comment by dotRarufu** [comment] 2024-06-27 01:50
> > > https://discord.gg/TSxymg7JTJ
> > > It's a 100% community server, but they help a lot of users
> > 
> > 
> > Thanks, I've solved my problem.
> 
> Could you please tell me how exactly you solved this problem?

in the discord server, there's a channel for hydra links. Click the link for that. Go to hydra launcher - Settings - Download Sources. Then paste sources you want

**Comment by thegrannychaseroperation** [comment] 2024-06-28 11:12
Closing this.

**Closed by thegrannychaseroperation** 2024-06-28 11:12 UTC
Labels: bug

**Comment by bressanmarcos** [comment] 2024-12-06 02:03
here's the freaking site with the links, geez
https://hydralinks.cloud/
