### ISSUE TITLE
[BUG] 32-bit

### ISSUE THREAD

**Issue by Sukuna0702** [hydralauncher/hydra#827] opened 2024-07-13 18:00 UTC
### Describe the bug

does not have 32-bit compatibility

### Steps to Reproduce

1

### Expected behavior

2

### Screenshots

2

### Operating System

windows 10

### Hydra Version

2.0.3

### Additional Information

simple problem, I just want 32 bits

**Comment by JackEnx** [comment] 2024-07-15 23:45
It's not a bug, we simply don't support 32-bit or  windows versions before the Win 10, and no, we won't be adding 32-bit.

**Closed by JackEnx** 2024-07-15 23:45 UTC
Labels: bug
