### ISSUE TITLE
[BUG] Black Screen

### ISSUE THREAD

**Issue by Mamao24** [hydralauncher/hydra#798] opened 2024-07-07 19:44 UTC
### Describe the bug

i start a game and everytime i get a black screen

### Steps to Reproduce

1. i open the game and get black screen

### Expected behavior

I expected the game to open without any black screen and with the online fix within it.

### Screenshots

![image](https://github.com/hydralauncher/hydra/assets/163359548/d2e42e8d-2ee9-43ca-a541-a08ae0166669)

### Operating System

Windows 11

### Hydra Version

2.0.3 "Leviticus"

### Additional Information

The game opens normally and then immediately shows a black screen over the game

**Comment by JackEnx** [comment] 2024-07-08 14:30
I didn't understand your problem very well, could you explain step by step, is the problem in on the hydra?

**Comment by Mamao24** [comment] 2024-07-08 18:31
The problem is not with the hydra, but when I start a game called "BIPED", it loads the credits normally and then the black screen appears, but it's only in this game.
I thought it was in the hydra

**Comment by JackEnx** [comment] 2024-07-08 18:41
as the problem is not specific to Hydra, I will be closing this issue.

**Closed by JackEnx** 2024-07-08 18:41 UTC
Labels: bug
