### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Martimsleite23** [hydralauncher/hydra#561] opened 2024-06-02 18:44 UTC
### Describe the bug

I go to Hydra and click on a game and the download option doesn't appear.

### Steps to Reproduce

3

### Expected behavior

The download option appears.

### Screenshots

![Captura de Ecrã (122)](https://github.com/hydralauncher/hydra/assets/171244473/96c52a95-24e8-40fb-b17c-ae5441cc46d0)

### Operating System

Windows 11

### Hydra Version

1.2.4

**Comment by zamitto** [comment] 2024-06-02 19:15
Duplicate of #526
Read the linked issue, an user posted a solution until we launch the next version with the proper fix

**Closed** 2024-06-02 19:15 UTC
Labels: bug
