### ISSUE TITLE
[BUG] Infinite metadata loading 0%

### ISSUE THREAD

**Issue by vdartsabvile** [hydralauncher/hydra#737] opened 2024-06-29 16:16 UTC
### Describe the bug

Infinite metadata loading 0%

### Steps to Reproduce

I'm downloading the "Higurashi ch4 Himatsubushi"

### Expected behavior

I wanted to download the game

### Operating System

Windows 11

### Hydra Version

v2.0.2

**Comment by vdartsabvile** [comment] 2024-06-29 16:30
I had to download via torrent via the magnet link "magnet:?xt=urn:btih:A8DBB95956EA0C16C5D91660540C6D0BAAE42CBC&#038;dn=Higurashi%20When%20They%20Cry%20Hou%20-%20Ch.4%20Himatsubushi-Gog&#038;tr=udp%3a%2f%2ftracker.openbittorrent.com%3a1337%2fannounce&#038;tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce"

**Comment by zamitto** [comment] 2024-06-29 18:30
Did you allow Hydra firewall windows permission when starting download? (And please don't post this kind of link here on Github)

**Comment by vdartsabvile** [comment] 2024-06-29 20:01
Yes, I allowed.

**Comment by Xxxsusx** [comment] 2024-06-30 01:13
This must be caused by the torrent (installation file). Have you by any chance closed (completely) Hydra and opened it after downloading the new version? In v2.0.2 this Metadata 0% bug was already fixed and I was also having problems but that was in v2.0.1

So there are two cases here that could be happening, you just updated Hydra v2.0.1 to v2.0.2 or the game file from this download source is too slow to be accessed/installed.

Have you tried pausing and resuming the download? If not, try. If nothing is solved yet, try downloading another game and see if this happens in other games as well. If this also occurs in other games, cancel the download, restart the system, open Hydra and start the download again to see if the problem has been solved.

If you've done all the options and still haven't solved it, I would recommend closing Hydra completely, uninstalling it and installing the latest version again. (Your library will return when you log into your account but you will probably have to locate the games' .exe files to play them)

**Comment by vdartsabvile** [comment] 2024-06-30 10:42
I have already stopped and canceled the download and tried to download another game, reinstalled Hydra several times through setup and portable

**Comment by Slurk-ss** [comment] 2024-07-01 11:57
Some time ago, I also encountered the problem of "infinite metadata loading" Here is a solution
![Screenshot_19](https://github.com/hydralauncher/hydra/assets/84561032/74933c36-07d5-4ffa-8de6-ac0c8179f5eb)
Go to your firewall settgings ==> fing "hydralauncher ==> give all acces.

**Comment by zamitto** [comment] 2024-09-23 15:00
Closing issue as no response in a long time.
If this error still happens in 2.1.7, feel free to open a new issue

**Closed by zamitto** 2024-09-23 15:00 UTC
Labels: bug
