### ISSUE TITLE
Real debrid support.

### ISSUE THREAD

**Issue by NLT33** [hydralauncher/hydra#69] opened 2024-04-22 17:25 UTC
Most people who know a thing or two about torrents usually have a debrid solution, i'd love to see this implemented.

**Comment by heliokrogerinfluencer** [comment] 2024-04-22 17:29
Duplicate of #51
I know a thing or two about torrents as you can see, but I don't know much about real debrid. But contributions are always welcome

**Closed** 2024-04-22 18:44 UTC
